spring:
  datasource:
    platform: postgres
    driver-class-name: com.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventory-service
    initialization-mode: always
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
